spring:
  application:
    name: ms-cliente
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    time-zone: America/Sao_Paulo

server:
  port: ${CLIENTE_SERVICE_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

ms-processo:
  url: ${MS_PROCESSO_URL}
